-- MySQL Script generated by MySQL Workbench
-- Sat Nov 16 18:35:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Test` DEFAULT CHARACTER SET utf8 ;
USE `Test` ;

-- -----------------------------------------------------
-- Table `Test`.`Voprosi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Test`.`Voprosi` (
  `idVopros` INT NOT NULL AUTO_INCREMENT,
  `Vopros` VARCHAR(1000) NULL DEFAULT NULL,
  `Otvet1` VARCHAR(1000) NULL DEFAULT NULL,
  `Otvet2` VARCHAR(1000) NULL DEFAULT NULL,
  `Otvet3` VARCHAR(1000) NULL DEFAULT NULL,
  `Correctanswer` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idVopros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Test`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Test`.`Rating` (
  `idRating` INT NOT NULL AUTO_INCREMENT,
  `Threshold` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idRating`),
  UNIQUE INDEX `idRating_UNIQUE` (`idRating` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Test`.`Result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Test`.`Result` (
  `idResult` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(100) NULL DEFAULT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Group` CHAR(100) NULL DEFAULT NULL,
  `Date` DATETIME(5) NULL DEFAULT NULL,
  `idRating` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idResult`),
  INDEX `idRating_idx` (`idRating` ASC) VISIBLE,
  CONSTRAINT `idRating`
    FOREIGN KEY (`idRating`)
    REFERENCES `Test`.`Rating` (`idRating`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
